/********************************************************************
* ex2aDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ex2aDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableex2aDict();
extern void G__cpp_setup_inheritanceex2aDict();
extern void G__cpp_setup_typetableex2aDict();
extern void G__cpp_setup_memvarex2aDict();
extern void G__cpp_setup_globalex2aDict();
extern void G__cpp_setup_memfuncex2aDict();
extern void G__cpp_setup_funcex2aDict();
extern void G__set_cpp_environmentex2aDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "example2a.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ex2aDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ex2aDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ex2aDictLN_TList;
extern G__linked_taginfo G__ex2aDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ex2aDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ex2aDictLN_TQObjSender;
extern G__linked_taginfo G__ex2aDictLN_TGWindow;
extern G__linked_taginfo G__ex2aDictLN_TGMainFrame;
extern G__linked_taginfo G__ex2aDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__ex2aDictLN_TGStatusBar;
extern G__linked_taginfo G__ex2aDictLN_MyMainFrame;

/* STUB derived class for protected member access */
