######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 29 11:31:06 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../Shm.h ../Header.h ../variables.h ../QT_variables.h
SOURCES += GUI_CREATOR.cpp main.cpp mainwindow.cpp mainwindow_DefinePixels.cpp
RESOURCES += Resource.qrc
