#!/bin/sh
#=============================================================================
#
#             --- CAEN SpA - Computing Systems Division ---
#
#  Library installation script.
#
#
#  Jul 2014 :   Created.
#
#=============================================================================

set -e
unset CDPATH

if [ `whoami` != "root" ]; then
    echo "You need to be root"
    exit 0
fi

ARCH=`uname -m`
if [ $ARCH != "x86_64" ]; then ARCH="x86"; fi
LIBPATH="lib/$ARCH"
LIB_BASENAME="libCAENDPPLib.so"
DPPLIBNAME="$LIB_BASENAME.1.4.4"
LIBDESTDIR="/usr/lib"
CORE_BASENAME="CAENDPPCore"
CORENAME="$CORE_BASENAME.bin"
COREDESTDIR="/usr/bin/"
COREDEPDIR="/etc/$CORE_BASENAME/"

# install dependencies
if [ ! -f /usr/lib/libCAENVME.so ]
then
    DEPLIBNAME="CAENVMELib-2.41"
    tar -xf Dependencies/$DEPLIBNAME.tgz
    cd $DEPLIBNAME/lib
    if [ "$ARCH" = "x86_64" ]; then
        sh install_x64
    else
        sh install
    fi
    cd -
    rm -rf $DEPLIBNAME
fi

if [ ! -f /usr/lib/libCAENComm.so ]
then
    DEPLIBNAME="CAENComm-1.2"
    tar -xf Dependencies/$DEPLIBNAME*.tgz
    cd $DEPLIBNAME/lib
    if [ "$ARCH" = "x86_64" ]; then
        sh install_x64
    else
        sh install
    fi
    cd -
    rm -rf $DEPLIBNAME
fi

# install libraries & CORE
CMD="install $LIBPATH/$LIB_BASENAME.* $LIBDESTDIR"
$CMD
mkdir -p "$COREDEPDIR"
CMD="install $LIBPATH/libCAENDigitizer.so.* $COREDEPDIR"
$CMD
install "$LIBPATH/$CORENAME" "$COREDESTDIR"
ln -sf "$LIBDESTDIR/$DPPLIBNAME" "$LIBDESTDIR/$LIB_BASENAME"
chmod a+x "$COREDESTDIR/$CORENAME"
/sbin/ldconfig
cp include/* /usr/include/

