/********************************************************************
* XRF_Fitter2Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error XRF_Fitter2Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableXRF_Fitter2Dict();
extern void G__cpp_setup_inheritanceXRF_Fitter2Dict();
extern void G__cpp_setup_typetableXRF_Fitter2Dict();
extern void G__cpp_setup_memvarXRF_Fitter2Dict();
extern void G__cpp_setup_globalXRF_Fitter2Dict();
extern void G__cpp_setup_memfuncXRF_Fitter2Dict();
extern void G__cpp_setup_funcXRF_Fitter2Dict();
extern void G__set_cpp_environmentXRF_Fitter2Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "example2a.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__XRF_Fitter2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__XRF_Fitter2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TList;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TTimer;
extern G__linked_taginfo G__XRF_Fitter2DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__XRF_Fitter2DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TQObjSender;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TGWindow;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TGMainFrame;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TGStatusBar;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TLegend;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TF1;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TLine;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TH1F;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TCanvas;
extern G__linked_taginfo G__XRF_Fitter2DictLN_TGTextButton;
extern G__linked_taginfo G__XRF_Fitter2DictLN_MyMainFrame;

/* STUB derived class for protected member access */
