######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 14 18:46:25 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp
