######################################################################
# Automatically generated by qmake (3.0) Wed May 10 11:39:58 2017
######################################################################

TEMPLATE = app
TARGET = maXRF-app
INCLUDEPATH += $$PWD/include/
QT += widgets\
      opengl \
      sql \
      xml \
      gui
CONFIG += c++14
CONFIG += qt warn_on thread
CONFIG += console

OBJECTS_DIR = $$PWD/build
MOC_DIR = $$PWD/build
RCC_DIR =  $$PWD/build
UI_DIR = $$PWD/build
DESTDIR = $$PWD/bin #Target file directory

# Input
HEADERS += \
  include/MAXRF/Shm.h \
  include/MAXRF/enums_and_wrappers.h \
  include/MAXRF/mainwindow.h \
  include/MAXRF/tty.h \
  include/MAXRF/types.h \
  include/MAXRF/utility_c.h
SOURCES += \
   src/external_programs.cpp \
   src/gui_interface_tty.cpp \
   src/main.cpp \
   src/mainwindow.cpp \
   src/mainwindow_conns.cpp \
   src/mainwindow_gui.cpp \
   src/mainwindow_menu.cpp \
   src/shm.cpp \
   src/tty_agent.cpp \
   src/utility_c.c
RESOURCES += \
  resources/resource.qrc
