######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 1 17:13:12 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../Header.h ../variables.h ../Shm.h
SOURCES += main.cpp mainwindow.cpp
