######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 27 15:31:54 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../Shm.h ../Header.h ../variables.h ../QT_variables.h
SOURCES += GUI_Creator.cpp main.cpp mainwindow.cpp TTY_motors.cpp XY_Z_Init.cpp
