######################################################################
# Automatically generated by qmake (3.0) Wed May 10 11:39:58 2017
######################################################################

TEMPLATE = app
TARGET = ADCXRF_USB
INCLUDEPATH += . ./src ./lib ./include
QT += widgets\
      opengl \
      sql \
      xml \
      gui
CONFIG += c++11
CONFIG += qt warn_on thread
CONFIG += console

# Input
HEADERS += ./include/*
SOURCES += ./src/*

