######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 26 22:06:34 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../Header.h ../variables.h ../Shm.h
SOURCES += GuiCreator.cpp main.cpp mainwindow.cpp
