#ifndef MAXRF_LIBRARIES_CONFIG_H
#define MAXRF_LIBRARIES_CONFIG_H

#include <QtCore/qglobal.h>

#if defined(MAXRF_LIBRARIES)
#  define MAXRF_LIBRARIES_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAXRF_LIBRARIES_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MAXRF_LIBRARIES_CONFIG_H
