######################################################################
# Automatically generated by qmake (3.0) Wed May 10 11:39:58 2017
######################################################################

TEMPLATE = app
TARGET = XRF_image

QT += widgets \
      gui \
      printsupport
CONFIG += c++14
CONFIG += qt warn_on thread
CONFIG += console

# Output directories for build steps
OBJECTS_DIR = $$PWD/build
MOC_DIR = $$PWD/build
RCC_DIR =  $$PWD/build
UI_DIR = $$PWD/build

# Output directory for target
DESTDIR = $$PWD/bin

#INPUT
INCLUDEPATH += $$PWD/include

HEADERS += \
  include/qcustomplot.h \
  include/MAXRF/types.h \
  include/MAXRF/conversion_routines.h \
  include/MAXRF/header_editor.h \
  include/MAXRF/image_display.h \
  include/MAXRF/viridis.h \
  include/MAXRF/xrf_image_widget.h \
  include/MAXRF/xrfimage.h \
  include/MAXRF/shared_memory.h
SOURCES += \
  src/qcustomplot.cpp \
  src/main.cpp \
  src/xrfimage_data.cpp \
  src/xrfimage_qlabel.cpp \
  src/xrfimage_widget.cpp \
  src/conversion_routines.cpp \
  src/header_editor.cpp
RESOURCES += \
  resources/resource.qrc

unix:!macx: LIBS += -L$$PWD/libs/ -lsharedmemory

INCLUDEPATH += $$PWD/libs
DEPENDPATH += $$PWD/libs

