######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 28 01:26:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += GuiCreator.cpp main.cpp mainwindow.cpp
