######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 26 09:35:29 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../Header.h
SOURCES += GuiCreator.cpp main.cpp mainwindow.cpp
