######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 15 11:11:05 2016
######################################################################

TEMPLATE = app
TARGET = rate
DEPENDPATH += .
INCLUDEPATH += /usr/local/qwt-6.1.4/include

QT += widgets\
      opengl \
      sql \
      xml \
      gui

CONFIG += c++17
CONFIG += qt warn_on thread


LIBS += -L/usr/local/qwt-6.1.4/lib -lqwt



# Input
HEADERS += Dial.h ../variables.h ../Shm.h
SOURCES += Dial.cpp
