######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 14 18:46:27 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../Header.h ../variables.h ../Shm.h
SOURCES += GuiCreator.cpp main.cpp mainwindow.cpp
