######################################################################
# Automatically generated by qmake (3.0) Wed May 10 11:39:58 2017
######################################################################

TEMPLATE = app
TARGET = maXRF-app
INCLUDEPATH += .
QT += widgets\
      opengl \
      sql \
      xml \
      gui
CONFIG += c++11
CONFIG += qt warn_on thread
CONFIG += console

# Input
HEADERS += mainwindow.h tty.h dpp.h ../Header.h ../Shm.h ../variables.h \
    ../qt_dependencies.h
SOURCES += main.cpp \
           dpp_gui.cpp \
           dpp_main.cpp \
           mainwindow.cpp \
           mainwindow_gui.cpp \
           mainwindow_menu.cpp \
           mainwindow_conns.cpp \
           external_programs.cpp \
           map_load.cpp \
           map_pixels.cpp \
           map_render.cpp \
           map_mouse.cpp \
           map_online.cpp \
           shm.cpp \
           tty.cpp \
           tty_device_t.cpp
RESOURCES += Resource.qrc
