######################################################################
# Automatically generated by qmake (3.0) Wed May 10 11:39:58 2017
######################################################################

TEMPLATE = app
TARGET = XRF_Scanner_Dev_3
INCLUDEPATH += .
QT += widgets\
      opengl \
      sql \
      xml \
      gui
CONFIG += c++11
CONFIG += qt warn_on thread
CONFIG += console

INCLUDEPATH += ../

# ---------------------------------------------------------------------------- #
# BUILD DIRECTORIES CONFIGURATION
# Output directories for temporary files and compiled binaries
# ---------------------------------------------------------------------------- #

# Output directory for the target
# For a shared library uncomment the following line
#DESTDIR = $$PWD/lib
# For a binary or executable file uncomment the following line
DESTDIR = $$PWD

# The directories where all the temporary files are written
MOC_DIR     = $$PWD/build
OBJECTS_DIR = $$PWD/build
RCC_DIR     = $$PWD/build
UI_DIR      = $$PWD/build

# ---------------------------------------------------------------------------- #
# SOURCES CONFIGURATION
# List of source, header, Qt Designer form, and Qt Resource files
# ---------------------------------------------------------------------------- #

# Input
HEADERS += \
  include/MAXRF/mainwindow.h \
  ../Header.h ../Shm.h ../variables.h ../QT_variables.h
SOURCES += \
  src/autofocus.cpp \
  src/Connections_Creator.cpp \
  src/export.cpp \
  src/export_pymca.cpp \
  src/external_programs.cpp \
  src/GUI_Creator.cpp \
  src/laser.cpp \
  src/main.cpp \
  src/mainwindow.cpp \
  src/mainwindow_DefinePixels.cpp \
  src/mainwindow_loadSHM.cpp \
  src/mainwindow_mouse.cpp \
  src/mainwindow_online.cpp \
  src/mainwindow_showMap.cpp \
  src/Menu.cpp \
  src/move_motors.cpp \
  src/ScanYX_XY.cpp \
  src/SHM_Creator.cpp \
  src/Stage_selection.cpp \
  src/TTY_motors.cpp \
  src/X_Init.cpp \
  src/Y_Init.cpp \
  src/Z_Init.cpp \
  src/WriteFileHeader.cpp
RESOURCES += Resource.qrc
